(function(g){var window=this;var E3=function(a,b){g.eR.call(this,a,b)},G3=function(a){g.EP.call(this,a);
var b=this;this.o=a;this.C=!1;this.F=new g.P(this);g.C(this,this.F);this.M=g.Bv(this.player.P().experiments,"web_player_show_music_in_this_video_graphic");this.Z=g.R(this.player.P().experiments,"web_player_show_music_in_this_video_no_ux");this.H=null;this.U=new g.J(function(){if(b.H){var d=b.H,e="/watch?v="+d.Fk,f=d.Lo,k=d.artistName,l="https://i.ytimg.com/vi/"+d.Fk+"/default.jpg";b.J.setVideoId(d.Fk);"video_thumbnail"===b.M&&b.G&&(b.G.ia("thumbnailSrc",l),d=b.u.o["ytp-attribution-inner-image-holder"])&&
(d.style.width="53px");b.w.ia("displayArtistName",k);b.w.ia("displaySongTitle",f);b.w.ia("premiumMusicVideoLink",e);b.u.ia("graphicPremiumMusicVideoLink",e);b.F.L(b.u.o["ytp-attribution-graphic-anchor"],"click",b.CK);g.NL(b.player,b.u.element,4);b.F.L(b.A.element,"click",b.vK);g.TL(b.o,b.A.element,!0);b.F.L(b.B.element,"click",b.aG);g.TL(b.o,b.B.element,!0);b.F.L(b.w.element,"click",b.MK);g.TL(b.o,b.w.element,!0);b.T.start()}b.Y.start()},5E3);
g.C(this,this.U);this.T=new g.J(function(){b.C||F3(b)},2E3);
g.C(this,this.T);this.O=new g.J(function(){b.C||(b.C=!0,F3(b))},7E3);
g.C(this,this.O);this.Y=new g.J(function(){g.K(b.u.element,"ytp-attribution-autohide")},1E4);
g.C(this,this.Y);"video_thumbnail"===this.M?this.G=new g.V({D:"img",I:"ytp-attribution-img",N:{src:"{{thumbnailSrc}}"}}):"headphone_icon"===this.M?this.G=new g.V({D:"div",I:"ytp-attribution-svg",K:[g.X?{D:"div",W:["ytp-icon","ytp-icon-music-in-this-video-headphone-icon"]}:{D:"svg",N:{fill:"none",height:"40",viewBox:"0 0 40 40",width:"40"},K:[{D:"rect",N:{fill:"#ff3838",height:"40",width:"40"}},{D:"path",N:{d:"M20.14 10C14.54 10 10 14.54 10 20.14V25.28C10.02 27.74 12.05 29.74 14.51 29.74H15.11C15.62 29.74 16.05 29.30 16.05 28.79V21.62C16.05 21.11 15.62 20.68 15.11 20.68H14.51C13.54 20.68 12.62 21.00 11.86 21.54V20.14C11.86 15.59 15.57 11.89 20.11 11.89C24.65 11.89 28.39 15.59 28.39 20.14V21.54C27.63 21.00 26.74 20.68 25.74 20.68H25.14C24.63 20.68 24.19 21.11 24.19 21.62V28.79C24.19 29.30 24.63 29.74 25.14 29.74H25.74C28.22 29.74 30.23 27.74 30.25 25.28V20.14C30.28 14.54 25.74 10 20.14 10H20.14Z",
fill:"white"}}]}]}):"music_notes_icon"===this.M&&(this.G=new g.V({D:"div",I:"ytp-attribution-svg",K:[g.X?{D:"div",W:["ytp-icon","ytp-icon-music-in-this-video-music-notes-icon"]}:{D:"svg",N:{fill:"none",height:"40",viewBox:"0 0 40 40",width:"40"},K:[{D:"rect",N:{fill:"#ff3838",height:"40",width:"40"}},{D:"path",N:{d:"M18.92 8.84V21.84C18.19 21.43 17.35 21.17 16.45 21.17C13.73 21.17 11.52 23.37 11.52 26.10C11.52 28.82 13.73 31.03 16.45 31.03C19.18 31.03 21.38 28.82 21.38 26.10V13.77H26.32V8.84H18.92Z",
fill:"white"}}]}]}));this.A=new g.V({D:"button",I:"ytp-attribution-chevron",K:[g.X?{D:"div",W:["ytp-icon","ytp-icon-attribution-open"]}:{D:"svg",N:{height:"100%",version:"1.1",viewBox:"0 0 32 32",width:"100%"},K:[{D:"circle",N:{cx:"16",cy:"16",fill:"white",r:"16"}},{D:"path",N:{d:"M 22.5,25.5 12,16 22.5,6.5 20,4 l -12,12 12,12 z",fill:"#000"}}]}]});g.PL(this.o,this.A.element,this.A,81564);this.B=new g.V({D:"div",I:"ytp-attribution-close-div",K:[{D:"button",I:"ytp-attribution-close",K:[g.pM()]}]});
g.PL(this.o,this.B.element,this.B,82133);this.w=new g.V({D:"a",I:"ytp-attribution-link-anchor",N:{href:"{{premiumMusicVideoLink}}"},K:[{D:"div",I:"ytp-attribution-text",K:[{D:"div",I:"ytp-attribution-track-title",V:"{{displaySongTitle}}"},{D:"div",I:"ytp-attribution-track-artist",V:"{{displayArtistName}}"}]}]});g.PL(this.o,this.w.element,this.w,88620);this.u=new g.V({D:"div",I:"ytp-attribution-wrapper",K:[this.A,{D:"div",I:"ytp-attribution",K:[{D:"a",I:"ytp-attribution-graphic-anchor",N:{href:"{{graphicPremiumMusicVideoLink}}"},
K:[{D:"div",I:"ytp-attribution-inner-image-holder",K:[this.G]}]},{D:"div",I:"ytp-attribution-inner-content-holder",K:[this.w,{D:"div",I:"ytp-attribution-watch-later"},this.B]}]}]});g.C(this,this.u);var c=g.hD(a);this.J=new E3(a,c);g.C(this,this.J);this.J.ba(this.u.o["ytp-attribution-watch-later"]);this.load()},F3=function(a){var b=a.u.o["ytp-attribution-inner-content-holder"];
b&&(g.yn(b,"active")?(g.An(b,"active"),g.An(a.A.element,"expanded")):(g.K(b,"active"),g.K(a.A.element,"expanded")));a.C||a.O.start()};
g.r(E3,g.eR);E3.prototype.setVideoId=function(a){this.Ta(!0);this.G=a};
E3.prototype.mz=function(){return this.G};
g.r(G3,g.EP);g.h=G3.prototype;g.h.load=function(){g.EP.prototype.load.call(this);this.H=null;this.F.L(this.player,"videodatachange",this.iy,this);this.iy()};
g.h.unload=function(){g.Kr(this.F);this.u&&g.OC(this.u);g.TL(this.o,this.A.element,!1);g.TL(this.o,this.B.element,!1);g.TL(this.o,this.w.element,!1);g.EP.prototype.unload.call(this)};
g.h.iy=function(){if(!this.H){var a;a:{if(a=this.player.getVideoData())if(a=a.Gj){b:{if((a=a.contents)&&(a=a.twoColumnWatchNextResults)&&(a=a.results)&&(a=a.results)&&(a=a.contents)&&0<a.length){a=g.p(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,b.videoSecondaryInfoRenderer)var c=b.videoSecondaryInfoRenderer;if(c){a={artistName:"",Lo:"",Fk:""};if((c=c.metadataRowContainer)&&(c=c.metadataRowContainerRenderer)&&c.rows){b=0;if(c.rows)for(var d=g.p(c.rows),e=d.next();!e.done;e=d.next())e=e.value,
e.metadataRowRenderer&&(e=e.metadataRowRenderer.title)&&"Song"===e.simpleText&&b++;if(!(1<b))for(c=g.p(c.rows),b=c.next();!b.done&&(d=b.value,d.metadataRowRenderer&&d.metadataRowRenderer.title&&d.metadataRowRenderer.contents&&0<d.metadataRowRenderer.contents.length&&(b=d.metadataRowRenderer.title,d=d.metadataRowRenderer.contents[0],"Artist"===b.simpleText&&(a.artistName=g.sA(d)),"Song"===b.simpleText&&(a.Lo=g.sA(d),d.runs&&d.runs[0]&&(b=d.runs[0].navigationEndpoint)&&(b=b.watchEndpoint)&&b.videoId&&
(a.Fk=b.videoId))),!a.artistName||!a.Lo);b=c.next());}break b}}a=null}if(a&&a.Fk&&a.artistName&&a.Lo)break a}a=null}a&&(this.H=a,this.Z||this.U.start())}};
g.h.CK=function(a){this.C=!0;var b=this.u.o["ytp-attribution-inner-content-holder"];b&&(g.yn(b,"active")?(g.SL(this.o,this.w.element),g.SM(a,this.player,!0)):(g.SL(this.o,this.A.element),g.SM(a,this.player,!1),F3(this)))};
g.h.vK=function(){this.C=!0;g.SL(this.o,this.A.element);F3(this)};
g.h.aG=function(){this.C=!0;g.SL(this.o,this.B.element);F3(this)};
g.h.MK=function(a){g.SL(this.o,this.w.element);g.SM(a,this.player,!0)};g.TP.attribution=G3;})(_yt_player);
